name: Repo Permission Check Action
author: "Benjamin Lanon <benjamin@lannonbr.com>"
description: Check if a user has specific access to this repo
inputs:
  permission:
    description: the max permission level required
    required: true
  user:
    description: the user to check, default to token's owner
    required: false
runs:
  using: "node12"
  main: "lib/index.js"
branding:
  icon: "check"
  color: "green"
